"use client";

import { useState } from "react";
import { ArrowUpRight, BrainCircuit, Github, Linkedin, Radio, ShieldCheck, Workflow } from "lucide-react";

type Project = { title: string; type: string; description: string; tags: string[]; href: string; featured?: boolean };
const projects: Project[] = [
  { title: "Proof of Trust", type: "GenAI / Web3", description: "An accountability layer for AI responses: human audits, model reputation, and immutable verification anchored to Solana.", tags: ["Next.js", "Solana", "Rust", "AI evaluation"], href: "https://github.com/ahmedjawad24/proof-of-trust", featured: true },
  { title: "FraudLens", type: "MLOps / Risk", description: "An imbalance-aware fraud screening system with validation-selected thresholds, analyst review queues, and batch inference.", tags: ["Python", "Scikit-learn", "Streamlit", "Evaluation"], href: "https://github.com/ahmedjawad24/credit-card-fraud-detection" },
  { title: "Explainable Retinal AI", type: "Applied AI", description: "A two-stage clinical vision pipeline with Grad-CAM heatmaps, FastAPI inference, and role-based workflows for review.", tags: ["PyTorch", "EfficientNet", "FastAPI", "Grad-CAM"], href: "https://github.com/ahmedjawad24/Explainable-retinal-disease-detection" },
  { title: "PEL Intelligence", type: "MLOps / Analytics", description: "A deployable power intelligence dashboard turning sensor signals into transparent predictions and operational history.", tags: ["Python", "Random Forest", "Dashboard", "Deployment"], href: "https://github.com/ahmedjawad24/PEL-Electronic-Intelligence" },
  { title: "CareBridge", type: "Agentic AI", description: "A healthcare-oriented agentic AI experience designed around useful, human-centered assistance.", tags: ["TypeScript", "Next.js", "Agents"], href: "https://github.com/ahmedjawad24/agentic_ai_hackathon" },
  { title: "Soil Crop Predictor", type: "Applied ML", description: "An accessible decision-support tool that maps soil measurements to crop recommendations.", tags: ["Python", "Streamlit", "Agriculture"], href: "https://github.com/ahmedjawad24/soil_crop_predictor" },
];
const filters = ["All", "GenAI / Web3", "Agentic AI", "MLOps / Risk", "Applied AI", "MLOps / Analytics", "Applied ML"];

export default function Home() {
  const [filter, setFilter] = useState("All");
  const visible = filter === "All" ? projects : projects.filter((project) => project.type === filter);
  return <main>
    <div className="shell">
      <nav className="nav"><a className="logo" href="#top"><span className="logo-mark">AJ</span> Ahmad Jawad</a><div className="nav-links"><a href="#work">Selected work</a><a href="#approach">Approach</a><a href="#contact">Contact</a></div><a className="button" href="https://github.com/ahmedjawad24" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15} /></a></nav>
      <section className="hero" id="top"><div><div className="kicker">Applied AI & MLOps Engineer · Open to global opportunities</div><h1>Building AI you can <em>trust.</em></h1><p className="hero-copy">I design and ship intelligent systems that move from ambitious idea to observable, useful product: agentic workflows, machine learning platforms, and responsible model experiences.</p><div className="actions"><a className="button primary" href="#work">Explore the work <ArrowUpRight size={16} /></a><a className="button" href="https://www.linkedin.com/in/ahmad-jawad-248870267" target="_blank" rel="noreferrer">Let&apos;s connect <Linkedin size={15} /></a></div></div><div className="signal"><div className="signal-grid" /><div className="signal-content"><div className="eyebrow">System status / 2026</div><h2>From model signal to human confidence.</h2><div className="signal-foot"><span><span className="pulse">●</span> Available for meaningful problems</span><span>EU · CN · KR · Global</span></div></div></div></section>
      <section className="section" id="work"><div className="section-head"><div><div className="kicker">01 / Selected systems</div><h2>Work with a point<br />of view.</h2></div><p className="section-intro">A portfolio of applied intelligence: systems built to be evaluated, explained, deployed, and improved.</p></div><div className="filters">{filters.map((item) => <button className={`filter ${filter === item ? "active" : ""}`} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="project-grid">{visible.map((project, index) => <a className={`project ${project.featured ? "featured" : ""}`} href={project.href} target="_blank" rel="noreferrer" key={project.title}><div className="project-top"><span className="project-index">0{index + 1} / {project.type}</span><ArrowUpRight className="project-link" size={20} /></div><div><h3>{project.title}</h3><p>{project.description}</p></div><div className="project-tags">{project.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></a>)}</div></section>
      <section className="section" id="approach"><div className="section-head"><div><div className="kicker">02 / How I work</div><h2>Useful beats<br />impressive.</h2></div><p className="section-intro">The strongest AI products respect both the machine and the person relying on it.</p></div><div className="capabilities"><div className="capability"><BrainCircuit size={22} /><h3>Build the intelligence</h3><p>Model selection, prompting, agent design, retrieval, and evaluation shaped around the real problem.</p></div><div className="capability"><Workflow size={22} /><h3>Operationalize the system</h3><p>Reproducible pipelines, versioned artifacts, APIs, dashboards, and deployment paths that survive contact with reality.</p></div><div className="capability"><ShieldCheck size={22} /><h3>Earn confidence</h3><p>Transparent metrics, explainability, human review, and explicit limits built into the experience.</p></div></div></section>
      <section className="section"><div className="about"><p className="about-copy">Curious about the edge where <strong>AI research</strong> becomes a product people can rely on.</p><div className="about-details"><p>I&apos;m Ahmad Jawad, an engineer working across generative AI, machine learning, and production-minded software. My projects range from AI accountability on Solana to clinical explainability and fraud operations.</p><p>I&apos;m especially interested in teams solving difficult problems with high standards for experimentation, reliability, and responsible deployment.</p><div className="actions"><a className="button" href="https://github.com/ahmedjawad24" target="_blank" rel="noreferrer"><Github size={15} /> GitHub profile</a><a className="button" href="mailto:ahmadjawad24@users.noreply.github.com">Email me <ArrowUpRight size={15} /></a></div></div></div></section>
    </div><section className="contact" id="contact"><div className="shell"><div className="kicker">03 / Start a conversation</div><h2>Have a hard problem?<br />Let&apos;s make it legible.</h2><a className="button" href="mailto:ahmadjawad24@users.noreply.github.com">Get in touch <ArrowUpRight size={16} /></a></div></section><div className="shell"><footer className="footer"><span>© 2026 Ahmad Jawad</span><span><Radio size={12} /> Built for the web · Deployed on Vercel</span></footer></div>
  </main>;
}
